### ISSUE TITLE
Fail to extracting 2D Poses Using diving48_example.ipynb

### ISSUE THREAD

**Issue by AgileChen3** [kennymckormick/pyskl#131]
Thank you for sharing this great repository. 

When i extract 2D skeleton for Diving48 Videos, an error has occurred.

bash tools/dist_run.sh tools/data/custom_2d_skeleton.py 1 --video-list data/Diving48_V2/diving48.list  --out data/Diving48_V2/diving48_annotions/
+ SCRIPT=tools/data/custom_2d_skeleton.py
+ GPUS=1
+ MKL_SERVICE_FORCE_INTEL=1
++ dirname tools/dist_run.sh
+ PYTHONPATH=tools/..:/opt/ros/noetic/lib/python3/dist-packages
+ python3 -m torch.distributed.launch --nproc_per_node=1 --master_port=19197 tools/data/custom_2d_skeleton.py --video-list data/Diving48_V2/diving48.list --out data/Diving48_V2/diving48_annotions/
Killing subprocess 542116
Traceback (most recent call last):
  File "/home/w/anaconda3/envs/pc3d/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/w/anaconda3/envs/pc3d/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/w/anaconda3/envs/pc3d/lib/python3.9/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/w/anaconda3/envs/pc3d/lib/python3.9/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/w/anaconda3/envs/pc3d/lib/python3.9/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/w/anaconda3/envs/pc3d/bin/python3', '-u', 'tools/data/custom_2d_skeleton.py', '--local_rank=0', '--video-list', 'data/Diving48_V2/diving48.list', '--out', 'data/Diving48_V2/diving48_annotions/']' died with <Signals.SIGSEGV: 11>.

Can anybody help me solve this issue?
Thanks!

**Comment by kennymckormick** [comment]
Recently I also met this problem. I guess the potential reason be a new version of gcc is used to compile the open-mmlab codebases, which lead to some errors. Now I have fixed it by using a very specific conda environment for this project. Please following the [new installation guide](https://github.com/kennymckormick/pyskl/blob/051a094f9de6cbe9ddeb1f3a8f2754629691ca42/README.md?plain=1#L46) to reinstall pyskl and see if the problem has been fixed now. 
Sorry for the late fix.

**Comment by AgileChen3** [comment]
thank for you reply，I have solve this problem with changing the import order，like this：
import argparse
import mmcv
import numpy as np
import os
import os.path as osp
import decord
import torch.distributed as dist
from mmcv.runner import get_dist_info, init_dist
from tqdm import tqdm
from mmdet.apis import inference_detector, init_detector
from mmpose.apis import inference_top_down_pose_model, init_pose_model
from pyskl.smp import mrlines

I do not why do this can solve the problem，I think it can help you to locating the source of problem.
