### ISSUE TITLE
problems when test the model of RGBPoseConv3D

### ISSUE THREAD

**Issue by whisper0411** [kennymckormick/pyskl#171]
I have downloaded the "NTU RGB+D" Dataset and compressed the raw rgb videos according to the readme.doc, however, when I use "Bash tools/dist_test.sh configs/rgbpose_conv3d/rgbpose_conv3d.py /home/buu/lixin/pyskl/ckpt/rgbpose_conv3d/rgbpose_conv3d.pth 1 --eval top_k_accuracy --out result.pkl" to test the pretrained model, the network occured an error as below:
  File "tools/test.py", line 184, in <module>
    main()
  File "tools/test.py", line 167, in main
    outputs = inference_pytorch(args, cfg, data_loader)
  File "tools/test.py", line 105, in inference_pytorch
    outputs = multi_gpu_test(model, data_loader, args.tmpdir)
  File "/home/buu/anaconda3/envs/pyskl/lib/python3.7/site-packages/mmcv/engine/test.py", line 70, in multi_gpu_test
    for i, data in enumerate(data_loader):
  File "/home/buu/anaconda3/envs/pyskl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/buu/anaconda3/envs/pyskl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/buu/anaconda3/envs/pyskl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/buu/anaconda3/envs/pyskl/lib/python3.7/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/buu/anaconda3/envs/pyskl/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/buu/anaconda3/envs/pyskl/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/buu/anaconda3/envs/pyskl/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/buu/lixin/pyskl/pyskl/datasets/base.py", line 322, in __getitem__
    return self.prepare_test_frames(idx) if self.test_mode else self.prepare_train_frames(idx)
  File "/home/buu/lixin/pyskl/pyskl/datasets/base.py", line 314, in prepare_test_frames
    return self.pipeline(results)
  File "/home/buu/lixin/pyskl/pyskl/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/buu/lixin/pyskl/pyskl/datasets/pipelines/multi_modality.py", line 99, in __call__
    imgs = self._decord_load_frames(video_reader, frame_inds)
  File "/home/buu/lixin/pyskl/pyskl/datasets/pipelines/loading.py", line 99, in _decord_load_frames
    imgs = container.get_batch(frame_inds).asnumpy()
  File "/home/buu/anaconda3/envs/pyskl/lib/python3.7/site-packages/decord/video_reader.py", line 174, in get_batch
    indices = _nd.array(self._validate_indices(indices))
  File "/home/buu/anaconda3/envs/pyskl/lib/python3.7/site-packages/decord/video_reader.py", line 132, in _validate_indices
    raise IndexError('Out of bound indices: {}'.format(indices[indices >= self._num_frame]))
IndexError: Out of bound indices: [ 64  74  99 128 146  61  78 107 120 139  74 106 122 133  73  76 100 125
 139  67  88 105 123 139  65  82 101 115 147  81 106 111 136  71  82 101
 111 144  70  90 103 112 135  71  74  98 113 145]

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 849461) of binary: /home/buu/anaconda3/envs/pyskl/bin/python
Traceback (most recent call last):
  File "/home/buu/anaconda3/envs/pyskl/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/buu/anaconda3/envs/pyskl/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/buu/anaconda3/envs/pyskl/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/buu/anaconda3/envs/pyskl/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/buu/anaconda3/envs/pyskl/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/buu/anaconda3/envs/pyskl/lib/python3.7/site-packages/torch/distributed/run.py", line 718, in run
    )(*cmd_args)
  File "/home/buu/anaconda3/envs/pyskl/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/buu/anaconda3/envs/pyskl/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/test.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
<img width="787" alt="image" src="https://user-images.githubusercontent.com/40971393/234889929-0e2bc101-a1c6-442c-818f-ef80d2c81815.png">
I have checked the dataset and I'm sure taht the number of the processed videos is right. Beg for help~~~

**Comment by dbzqyyy** [comment]
hi, I'm having the same problem, can you tell me how to fix it, thanks
