### ISSUE TITLE
Error when using NTURGB+D [3D Skeleton] and NTURGB+D 120 [3D Skeleton] as dataset

### ISSUE THREAD

**Issue by Gbouna** [kennymckormick/pyskl#173]
Hello,

When running the command below using either the NTURGB+D [3D Skeleton] or NTURGB+D 120 [3D Skeleton] as dataset, I encountered the error below. Note that i downloaded the processed skeleton data from https://github.com/kennymckormick/pyskl/tree/main/tools/data

> bash tools/dist_train.sh configs/posec3d/slowonly_r50_ntu60_xsub/joint.py 2 --validate --test-last --test-best

here are the error messages.

>   File "/home/arptracker/Vincent/action_recognition/pyskl/tools/train.py", line 164, in <module>
> dict_keys(['frame_dir', 'label', 'keypoint', 'total_frames', 'modality', 'start_index', 'test_mode', 'frame_inds', 'clip_len', 'frame_interval', 'num_clips'])
> dict_keys(['frame_dir', 'label', 'keypoint', 'total_frames', 'modality', 'start_index', 'test_mode', 'frame_inds', 'clip_len', 'frame_interval', 'num_clips'])
> dict_keys(['frame_dir', 'label', 'keypoint', 'total_frames', 'modality', 'start_index', 'test_mode', 'frame_inds', 'clip_len', 'frame_interval', 'num_clips'])
>     main()
>   File "/home/arptracker/Vincent/action_recognition/pyskl/tools/train.py", line 156, in main
>     train_model(model, datasets, cfg, validate=args.validate, test=test_option, timestamp=timestamp, meta=meta)
>   File "/home/arptracker/Vincent/action_recognition/pyskl/pyskl/apis/train.py", line 144, in train_model
>     runner.run(data_loaders, cfg.workflow, cfg.total_epochs)dict_keys(['frame_dir', 'label', 'keypoint', 'total_frames', 'modality', 'start_index', 'test_mode', 'frame_inds', 'clip_len', 'frame_interval', 'num_clips'])
> 
>   File "/home/arptracker/Vincent/action_recognition/venv/lib/python3.10/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
>     epoch_runner(data_loaders[i], **kwargs)
>   File "/home/arptracker/Vincent/action_recognition/venv/lib/python3.10/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
>     for i, data_batch in enumerate(self.data_loader):
>   File "/home/arptracker/Vincent/action_recognition/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
>     data = self._next_data()
>   File "/home/arptracker/Vincent/action_recognition/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
>     return self._process_data(data)
>   File "/home/arptracker/Vincent/action_recognition/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
> dict_keys(['frame_dir', 'label', 'keypoint', 'total_frames', 'modality', 'start_index', 'test_mode', 'frame_inds', 'clip_len', 'frame_interval', 'num_clips'])
>     data.reraise()
> dict_keys(['frame_dir', 'label', 'keypoint', 'total_frames', 'modality', 'start_index', 'test_mode', 'frame_inds', 'clip_len', 'frame_interval', 'num_clips'])
> dict_keys(['frame_dir', 'label', 'keypoint', 'total_frames', 'modality', 'start_index', 'test_mode', 'frame_inds', 'clip_len', 'frame_interval', 'num_clips'])
>   File "/home/arptracker/Vincent/action_recognition/venv/lib/python3.10/site-packages/torch/_utils.py", line 644, in reraise
>     raise exception
> KeyError: Caught KeyError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/home/arptracker/Vincent/action_recognition/venv/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/home/arptracker/Vincent/action_recognition/venv/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/home/arptracker/Vincent/action_recognition/venv/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/home/arptracker/Vincent/action_recognition/pyskl/pyskl/datasets/dataset_wrappers.py", line 34, in __getitem__
>     return self.dataset[idx % self._ori_len]
>   File "/home/arptracker/Vincent/action_recognition/pyskl/pyskl/datasets/base.py", line 322, in __getitem__
>     return self.prepare_test_frames(idx) if self.test_mode else self.prepare_train_frames(idx)
>   File "/home/arptracker/Vincent/action_recognition/pyskl/pyskl/datasets/base.py", line 273, in prepare_train_frames
>     return self.pipeline(results)
>   File "/home/arptracker/Vincent/action_recognition/pyskl/pyskl/datasets/pipelines/compose.py", line 41, in __call__
>     data = t(data)
>   File "/home/arptracker/Vincent/action_recognition/pyskl/pyskl/datasets/pipelines/augmentations.py", line 61, in __call__
>     img_shape = results['img_shape']
> KeyError: 'img_shape'
> 
> dict_keys(['frame_dir', 'label', 'keypoint', 'total_frames', 'modality', 'start_index', 'test_mode', 'frame_inds', 'clip_len', 'frame_interval', 'num_clips'])
> dict_keys(['frame_dir', 'label', 'keypoint', 'total_frames', 'modality', 'start_index', 'test_mode', 'frame_inds', 'clip_len', 'frame_interval', 'num_clips'])
> dict_keys(['frame_dir', 'label', 'keypoint', 'total_frames', 'modality', 'start_index', 'test_mode', 'frame_inds', 'clip_len', 'frame_interval', 'num_clips'])
> dict_keys(['frame_dir', 'label', 'keypoint', 'total_frames', 'modality', 'start_index', 'test_mode', 'frame_inds', 'clip_len', 'frame_interval', 'num_clips'])
> Traceback (most recent call last):
>   File "/home/arptracker/Vincent/action_recognition/pyskl/tools/train.py", line 164, in <module>
> dict_keys(['frame_dir', 'label', 'keypoint', 'total_frames', 'modality', 'start_index', 'test_mode', 'frame_inds', 'clip_len', 'frame_interval', 'num_clips'])
> dict_keys(['frame_dir', 'label', 'keypoint', 'total_frames', 'modality', 'start_index', 'test_mode', 'frame_inds', 'clip_len', 'frame_interval', 'num_clips'])
>     main()
>   File "/home/arptracker/Vincent/action_recognition/pyskl/tools/train.py", line 156, in main
>     train_model(model, datasets, cfg, validate=args.validate, test=test_option, timestamp=timestamp, meta=meta)
>   File "/home/arptracker/Vincent/action_recognition/pyskl/pyskl/apis/train.py", line 144, in train_model
>     runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
>   File "/home/arptracker/Vincent/action_recognition/venv/lib/python3.10/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
>     epoch_runner(data_loaders[i], **kwargs)
>   File "/home/arptracker/Vincent/action_recognition/venv/lib/python3.10/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
>     for i, data_batch in enumerate(self.data_loader):
>   File "/home/arptracker/Vincent/action_recognition/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
> dict_keys(['frame_dir', 'label', 'keypoint', 'total_frames', 'modality', 'start_index', 'test_mode', 'frame_inds', 'clip_len', 'frame_interval', 'num_clips'])
>     data = self._next_data()
>   File "/home/arptracker/Vincent/action_recognition/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
>     return self._process_data(data)
>   File "/home/arptracker/Vincent/action_recognition/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
>     data.reraise()
>   File "/home/arptracker/Vincent/action_recognition/venv/lib/python3.10/site-packages/torch/_utils.py", line 644, in reraise
>     raise exception
> KeyError: Caught KeyError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/home/arptracker/Vincent/action_recognition/venv/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/home/arptracker/Vincent/action_recognition/venv/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/home/arptracker/Vincent/action_recognition/venv/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/home/arptracker/Vincent/action_recognition/pyskl/pyskl/datasets/dataset_wrappers.py", line 34, in __getitem__
>     return self.dataset[idx % self._ori_len]
>   File "/home/arptracker/Vincent/action_recognition/pyskl/pyskl/datasets/base.py", line 322, in __getitem__
>     return self.prepare_test_frames(idx) if self.test_mode else self.prepare_train_frames(idx)
>   File "/home/arptracker/Vincent/action_recognition/pyskl/pyskl/datasets/base.py", line 273, in prepare_train_frames
>     return self.pipeline(results)
>   File "/home/arptracker/Vincent/action_recognition/pyskl/pyskl/datasets/pipelines/compose.py", line 41, in __call__
>     data = t(data)
>   File "/home/arptracker/Vincent/action_recognition/pyskl/pyskl/datasets/pipelines/augmentations.py", line 61, in __call__
>     img_shape = results['img_shape']
> KeyError: 'img_shape'
> 
> dict_keys(['frame_dir', 'label', 'keypoint', 'total_frames', 'modality', 'start_index', 'test_mode', 'frame_inds', 'clip_len', 'frame_interval', 'num_clips'])
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 23312) of binary: /home/arptracker/Vincent/action_recognition/venv/bin/python
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/home/arptracker/Vincent/action_recognition/venv/lib/python3.10/site-packages/torch/distributed/launch.py", line 196, in <module>
>     main()
>   File "/home/arptracker/Vincent/action_recognition/venv/lib/python3.10/site-packages/torch/distributed/launch.py", line 192, in main
>     launch(args)
>   File "/home/arptracker/Vincent/action_recognition/venv/lib/python3.10/site-packages/torch/distributed/launch.py", line 177, in launch
>     run(args)
>   File "/home/arptracker/Vincent/action_recognition/venv/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
>     elastic_launch(
>   File "/home/arptracker/Vincent/action_recognition/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/home/arptracker/Vincent/action_recognition/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by kennymckormick** [comment]
Hi, [Gbouna](https://github.com/Gbouna), 
The problem is that PoseConv3D only applies to 2D skeletons, so you can not directly use 3D skeletons for training and testing (which will lead to the reported errors).

**Comment by 223d** [comment]
Hi,May I ask what is the storage location for the NTURGB.pkl file? And what is the relationship with the config path？ thankyou

**Comment by 223d** [comment]
I run bash tools/dist_train.sh configs/posec3d/slowonly_r50_ntu60_xsub/joint.py 1  
2024-01-08 14:56:14,429 - pyskl - INFO - Set random seed to 557811968, deterministic: False
Traceback (most recent call last):
  File "/home/zlq/miniconda3/envs/pyskl/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/zlq/project/pyskl-main/pyskl/datasets/pose_dataset.py", line 58, in __init__
    ann_file, pipeline, start_index=0, modality=modality, memcached=memcached, mc_cfg=mc_cfg, **kwargs)
  File "/home/zlq/project/pyskl-main/pyskl/datasets/base.py", line 72, in __init__
    self.video_infos = self.load_annotations()
  File "/home/zlq/project/pyskl-main/pyskl/datasets/pose_dataset.py", line 89, in load_annotations
    return self.load_pkl_annotations()
  File "/home/zlq/project/pyskl-main/pyskl/datasets/pose_dataset.py", line 92, in load_pkl_annotations
    data = mmcv.load(self.ann_file)
  File "/home/zlq/miniconda3/envs/pyskl/lib/python3.7/site-packages/mmcv/fileio/io.py", line 61, in load
    obj = handler.load_from_fileobj(f, **kwargs)
  File "/home/zlq/miniconda3/envs/pyskl/lib/python3.7/site-packages/mmcv/fileio/handlers/pickle_handler.py", line 12, in load_from_fileobj
    return pickle.load(file, **kwargs)
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zlq/miniconda3/envs/pyskl/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/zlq/project/pyskl-main/pyskl/datasets/dataset_wrappers.py", line 25, in __init__
    self.dataset = build_dataset(dataset)
  File "/home/zlq/project/pyskl-main/pyskl/datasets/builder.py", line 37, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/zlq/miniconda3/envs/pyskl/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
EOFError: PoseDataset: Ran out of input
May I ask what the problem is?
