### ISSUE TITLE
How can I train a gesture recognition model with a dynamic dataset?

### ISSUE THREAD

**Issue by MJCC-wht** [kennymckormick/pyskl#213]
I want to use stgcn++, so I mean which config file can I use? Or I need to create my own config file?

**Comment by karryor** [comment]
Hello, have you trained gesture recognition with stgcn++? Can you share it?

**Comment by MJCC-wht** [comment]
> Hello, have you trained gesture recognition with stgcn++? Can you share it?

I just train simply, the config file content is below:

graph = 'handmp'
modality = 'j'

model = dict(
    type='RecognizerGCN',
    backbone=dict(
        type='STGCN',
        in_channels=2,
        gcn_adaptive='init',
        gcn_with_res=True,
        tcn_type='mstcn',
        num_stages=6,
        down_stages=[6],
        inflate_stages=[6],
        graph_cfg=dict(layout=graph, mode='spatial')),
    cls_head=dict(type='GCNHead', num_classes=2, in_channels=128))

dataset_type = 'GestureDataset'
ann_file = 'data/labdata/smoke_output_final.pkl'
load_from = 'demo/hagrid.pth'
train_pipeline = [
    dict(type='PreNormalize2D', threshold=0, mode='auto'),
    dict(type='GenSkeFeat', dataset=graph, feats=[modality]),
    dict(type='UniformSample', clip_len=10, num_clips=1),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', num_person=1),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]
val_pipeline = [
    dict(type='PreNormalize2D', threshold=0, mode='auto'),
    dict(type='GenSkeFeat', dataset=graph, feats=[modality]),
    dict(type='UniformSample', clip_len=10, num_clips=1),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', num_person=1),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]
test_pipeline = [
    dict(type='PreNormalize2D', threshold=0, mode='auto'),
    dict(type='GenSkeFeat', dataset=graph, feats=[modality]),
    dict(type='UniformSample', clip_len=10, num_clips=1),
    dict(type='PoseDecode'),
    dict(type='FormatGCNInput', num_person=1),
    dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['keypoint'])
]

data = dict(
    videos_per_gpu=16,
    workers_per_gpu=2,
    test_dataloader=dict(videos_per_gpu=1),
    train=dict(
        type='RepeatDataset',
        times=5,
        dataset=dict(type=dataset_type, ann_file=ann_file, pipeline=train_pipeline, split='labdata_train')),
    val=dict(type=dataset_type, ann_file=ann_file, pipeline=val_pipeline, split='labdata_val'),
    test=dict(type=dataset_type, ann_file=ann_file, pipeline=test_pipeline, split='labdata_val'))

# optimizer
optimizer = dict(type='SGD', lr=0.1, momentum=0.9, weight_decay=0.0005, nesterov=True)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(policy='CosineAnnealing', min_lr=0, by_epoch=False)
total_epochs = 25
checkpoint_config = dict(interval=1)
evaluation = dict(interval=1, metrics=['top_k_accuracy'])
log_config = dict(interval=1, hooks=[dict(type='TextLoggerHook')])

# runtime settings
log_level = 'INFO'
work_dir = './work_dirs/stgcn++/stgcn++_labdata_hrnet/hand_j'

then just use the script bash file to train

**Comment by karryor** [comment]
Hello, thank you for your reply. There is one more question, I have learned that STGCN network classifs behaviors for consecutive frames. Did you add tracking network? I didn't see it in the configuration file.




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "kennymckormick/pyskl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月16日(星期二) 下午2:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kennymckormick/pyskl] How can I train a gesture recognition model with a dynamic dataset? (Issue #213)





  
Hello, have you trained gesture recognition with stgcn++? Can you share it?
  
I just train simply, the config file content is below:
 
graph = 'handmp'
 modality = 'j'
 
model = dict(
 type='RecognizerGCN',
 backbone=dict(
 type='STGCN',
 in_channels=2,
 gcn_adaptive='init',
 gcn_with_res=True,
 tcn_type='mstcn',
 num_stages=6,
 down_stages=[6],
 inflate_stages=[6],
 graph_cfg=dict(layout=graph, mode='spatial')),
 cls_head=dict(type='GCNHead', num_classes=2, in_channels=128))
 
dataset_type = 'GestureDataset'
 ann_file = 'data/labdata/smoke_output_final.pkl'
 load_from = 'demo/hagrid.pth'
 train_pipeline = [
 dict(type='PreNormalize2D', threshold=0, mode='auto'),
 dict(type='GenSkeFeat', dataset=graph, feats=[modality]),
 dict(type='UniformSample', clip_len=10, num_clips=1),
 dict(type='PoseDecode'),
 dict(type='FormatGCNInput', num_person=1),
 dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
 dict(type='ToTensor', keys=['keypoint'])
 ]
 val_pipeline = [
 dict(type='PreNormalize2D', threshold=0, mode='auto'),
 dict(type='GenSkeFeat', dataset=graph, feats=[modality]),
 dict(type='UniformSample', clip_len=10, num_clips=1),
 dict(type='PoseDecode'),
 dict(type='FormatGCNInput', num_person=1),
 dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
 dict(type='ToTensor', keys=['keypoint'])
 ]
 test_pipeline = [
 dict(type='PreNormalize2D', threshold=0, mode='auto'),
 dict(type='GenSkeFeat', dataset=graph, feats=[modality]),
 dict(type='UniformSample', clip_len=10, num_clips=1),
 dict(type='PoseDecode'),
 dict(type='FormatGCNInput', num_person=1),
 dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]),
 dict(type='ToTensor', keys=['keypoint'])
 ]
 
data = dict(
 videos_per_gpu=16,
 workers_per_gpu=2,
 test_dataloader=dict(videos_per_gpu=1),
 train=dict(
 type='RepeatDataset',
 times=5,
 dataset=dict(type=dataset_type, ann_file=ann_file, pipeline=train_pipeline, split='labdata_train')),
 val=dict(type=dataset_type, ann_file=ann_file, pipeline=val_pipeline, split='labdata_val'),
 test=dict(type=dataset_type, ann_file=ann_file, pipeline=test_pipeline, split='labdata_val'))
 
optimizer
 
optimizer = dict(type='SGD', lr=0.1, momentum=0.9, weight_decay=0.0005, nesterov=True)
 optimizer_config = dict(grad_clip=None)
 
learning policy
 
lr_config = dict(policy='CosineAnnealing', min_lr=0, by_epoch=False)
 total_epochs = 25
 checkpoint_config = dict(interval=1)
 evaluation = dict(interval=1, metrics=['top_k_accuracy'])
 log_config = dict(interval=1, hooks=[dict(type='TextLoggerHook')])
 
runtime settings
 
log_level = 'INFO'
 work_dir = './work_dirs/stgcn++/stgcn++_labdata_hrnet/hand_j'
 
then just use the script bash file to train

**Comment by MJCC-wht** [comment]
> Hello, thank you for your reply. There is one more question, I have learned that STGCN network classifs behaviors for consecutive frames. Did you add tracking network? I didn't see it in the configuration file.
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "kennymckormick/pyskl" ***@***.***&gt;; 发送时间:&nbsp;2024年1月16日(星期二) 下午2:55 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [kennymckormick/pyskl] How can I train a gesture recognition model with a dynamic dataset? (Issue #213) Hello, have you trained gesture recognition with stgcn++? Can you share it? I just train simply, the config file content is below: graph = 'handmp' modality = 'j' model = dict( type='RecognizerGCN', backbone=dict( type='STGCN', in_channels=2, gcn_adaptive='init', gcn_with_res=True, tcn_type='mstcn', num_stages=6, down_stages=[6], inflate_stages=[6], graph_cfg=dict(layout=graph, mode='spatial')), cls_head=dict(type='GCNHead', num_classes=2, in_channels=128)) dataset_type = 'GestureDataset' ann_file = 'data/labdata/smoke_output_final.pkl' load_from = 'demo/hagrid.pth' train_pipeline = [ dict(type='PreNormalize2D', threshold=0, mode='auto'), dict(type='GenSkeFeat', dataset=graph, feats=[modality]), dict(type='UniformSample', clip_len=10, num_clips=1), dict(type='PoseDecode'), dict(type='FormatGCNInput', num_person=1), dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]), dict(type='ToTensor', keys=['keypoint']) ] val_pipeline = [ dict(type='PreNormalize2D', threshold=0, mode='auto'), dict(type='GenSkeFeat', dataset=graph, feats=[modality]), dict(type='UniformSample', clip_len=10, num_clips=1), dict(type='PoseDecode'), dict(type='FormatGCNInput', num_person=1), dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]), dict(type='ToTensor', keys=['keypoint']) ] test_pipeline = [ dict(type='PreNormalize2D', threshold=0, mode='auto'), dict(type='GenSkeFeat', dataset=graph, feats=[modality]), dict(type='UniformSample', clip_len=10, num_clips=1), dict(type='PoseDecode'), dict(type='FormatGCNInput', num_person=1), dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]), dict(type='ToTensor', keys=['keypoint']) ] data = dict( videos_per_gpu=16, workers_per_gpu=2, test_dataloader=dict(videos_per_gpu=1), train=dict( type='RepeatDataset', times=5, dataset=dict(type=dataset_type, ann_file=ann_file, pipeline=train_pipeline, split='labdata_train')), val=dict(type=dataset_type, ann_file=ann_file, pipeline=val_pipeline, split='labdata_val'), test=dict(type=dataset_type, ann_file=ann_file, pipeline=test_pipeline, split='labdata_val')) optimizer optimizer = dict(type='SGD', lr=0.1, momentum=0.9, weight_decay=0.0005, nesterov=True) optimizer_config = dict(grad_clip=None) learning policy lr_config = dict(policy='CosineAnnealing', min_lr=0, by_epoch=False) total_epochs = 25 checkpoint_config = dict(interval=1) evaluation = dict(interval=1, metrics=['top_k_accuracy']) log_config = dict(interval=1, hooks=[dict(type='TextLoggerHook')]) runtime settings log_level = 'INFO' work_dir = './work_dirs/stgcn++/stgcn++_labdata_hrnet/hand_j' then just use the script bash file to train — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

Sorry, I didn't. Maybe you need to try it on your own.

**Comment by karryor** [comment]
OK，thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kennymckormick/pyskl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月17日(星期三) 下午4:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kennymckormick/pyskl] How can I train a gesture recognition model with a dynamic dataset? (Issue #213)





  
Hello, thank you for your reply. There is one more question, I have learned that STGCN network classifs behaviors for consecutive frames. Did you add tracking network? I didn't see it in the configuration file.
 …
 ------------------ 原始邮件 ------------------ 发件人: "kennymckormick/pyskl" @.&gt;; 发送时间:&nbsp;2024年1月16日(星期二) 下午2:55 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [kennymckormick/pyskl] How can I train a gesture recognition model with a dynamic dataset? (Issue #213) Hello, have you trained gesture recognition with stgcn++? Can you share it? I just train simply, the config file content is below: graph = 'handmp' modality = 'j' model = dict( type='RecognizerGCN', backbone=dict( type='STGCN', in_channels=2, gcn_adaptive='init', gcn_with_res=True, tcn_type='mstcn', num_stages=6, down_stages=[6], inflate_stages=[6], graph_cfg=dict(layout=graph, mode='spatial')), cls_head=dict(type='GCNHead', num_classes=2, in_channels=128)) dataset_type = 'GestureDataset' ann_file = 'data/labdata/smoke_output_final.pkl' load_from = 'demo/hagrid.pth' train_pipeline = [ dict(type='PreNormalize2D', threshold=0, mode='auto'), dict(type='GenSkeFeat', dataset=graph, feats=[modality]), dict(type='UniformSample', clip_len=10, num_clips=1), dict(type='PoseDecode'), dict(type='FormatGCNInput', num_person=1), dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]), dict(type='ToTensor', keys=['keypoint']) ] val_pipeline = [ dict(type='PreNormalize2D', threshold=0, mode='auto'), dict(type='GenSkeFeat', dataset=graph, feats=[modality]), dict(type='UniformSample', clip_len=10, num_clips=1), dict(type='PoseDecode'), dict(type='FormatGCNInput', num_person=1), dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]), dict(type='ToTensor', keys=['keypoint']) ] test_pipeline = [ dict(type='PreNormalize2D', threshold=0, mode='auto'), dict(type='GenSkeFeat', dataset=graph, feats=[modality]), dict(type='UniformSample', clip_len=10, num_clips=1), dict(type='PoseDecode'), dict(type='FormatGCNInput', num_person=1), dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]), dict(type='ToTensor', keys=['keypoint']) ] data = dict( videos_per_gpu=16, workers_per_gpu=2, test_dataloader=dict(videos_per_gpu=1), train=dict( type='RepeatDataset', times=5, dataset=dict(type=dataset_type, ann_file=ann_file, pipeline=train_pipeline, split='labdata_train')), val=dict(type=dataset_type, ann_file=ann_file, pipeline=val_pipeline, split='labdata_val'), test=dict(type=dataset_type, ann_file=ann_file, pipeline=test_pipeline, split='labdata_val')) optimizer optimizer = dict(type='SGD', lr=0.1, momentum=0.9, weight_decay=0.0005, nesterov=True) optimizer_config = dict(grad_clip=None) learning policy lr_config = dict(policy='CosineAnnealing', min_lr=0, by_epoch=False) total_epochs = 25 checkpoint_config = dict(interval=1) evaluation = dict(interval=1, metrics=['top_k_accuracy']) log_config = dict(interval=1, hooks=[dict(type='TextLoggerHook')]) runtime settings log_level = 'INFO' work_dir = './work_dirs/stgcn++/stgcn++_labdata_hrnet/hand_j' then just use the script bash file to train — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
Sorry, I didn't. Maybe you need to try it on your own.

**Comment by karryor** [comment]
Hello, can you share the 40 categories of gesture recognition and corresponding gesture images， thank you？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kennymckormick/pyskl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月17日(星期三) 下午4:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kennymckormick/pyskl] How can I train a gesture recognition model with a dynamic dataset? (Issue #213)





  
Hello, thank you for your reply. There is one more question, I have learned that STGCN network classifs behaviors for consecutive frames. Did you add tracking network? I didn't see it in the configuration file.
 …
 ------------------ 原始邮件 ------------------ 发件人: "kennymckormick/pyskl" @.&gt;; 发送时间:&nbsp;2024年1月16日(星期二) 下午2:55 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [kennymckormick/pyskl] How can I train a gesture recognition model with a dynamic dataset? (Issue #213) Hello, have you trained gesture recognition with stgcn++? Can you share it? I just train simply, the config file content is below: graph = 'handmp' modality = 'j' model = dict( type='RecognizerGCN', backbone=dict( type='STGCN', in_channels=2, gcn_adaptive='init', gcn_with_res=True, tcn_type='mstcn', num_stages=6, down_stages=[6], inflate_stages=[6], graph_cfg=dict(layout=graph, mode='spatial')), cls_head=dict(type='GCNHead', num_classes=2, in_channels=128)) dataset_type = 'GestureDataset' ann_file = 'data/labdata/smoke_output_final.pkl' load_from = 'demo/hagrid.pth' train_pipeline = [ dict(type='PreNormalize2D', threshold=0, mode='auto'), dict(type='GenSkeFeat', dataset=graph, feats=[modality]), dict(type='UniformSample', clip_len=10, num_clips=1), dict(type='PoseDecode'), dict(type='FormatGCNInput', num_person=1), dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]), dict(type='ToTensor', keys=['keypoint']) ] val_pipeline = [ dict(type='PreNormalize2D', threshold=0, mode='auto'), dict(type='GenSkeFeat', dataset=graph, feats=[modality]), dict(type='UniformSample', clip_len=10, num_clips=1), dict(type='PoseDecode'), dict(type='FormatGCNInput', num_person=1), dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]), dict(type='ToTensor', keys=['keypoint']) ] test_pipeline = [ dict(type='PreNormalize2D', threshold=0, mode='auto'), dict(type='GenSkeFeat', dataset=graph, feats=[modality]), dict(type='UniformSample', clip_len=10, num_clips=1), dict(type='PoseDecode'), dict(type='FormatGCNInput', num_person=1), dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]), dict(type='ToTensor', keys=['keypoint']) ] data = dict( videos_per_gpu=16, workers_per_gpu=2, test_dataloader=dict(videos_per_gpu=1), train=dict( type='RepeatDataset', times=5, dataset=dict(type=dataset_type, ann_file=ann_file, pipeline=train_pipeline, split='labdata_train')), val=dict(type=dataset_type, ann_file=ann_file, pipeline=val_pipeline, split='labdata_val'), test=dict(type=dataset_type, ann_file=ann_file, pipeline=test_pipeline, split='labdata_val')) optimizer optimizer = dict(type='SGD', lr=0.1, momentum=0.9, weight_decay=0.0005, nesterov=True) optimizer_config = dict(grad_clip=None) learning policy lr_config = dict(policy='CosineAnnealing', min_lr=0, by_epoch=False) total_epochs = 25 checkpoint_config = dict(interval=1) evaluation = dict(interval=1, metrics=['top_k_accuracy']) log_config = dict(interval=1, hooks=[dict(type='TextLoggerHook')]) runtime settings log_level = 'INFO' work_dir = './work_dirs/stgcn++/stgcn++_labdata_hrnet/hand_j' then just use the script bash file to train — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
Sorry, I didn't. Maybe you need to try it on your own.

**Comment by MJCC-wht** [comment]
> Hello, can you share the 40 categories of gesture recognition and corresponding gesture images， thank you？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "kennymckormick/pyskl" ***@***.***&gt;; 发送时间:&nbsp;2024年1月17日(星期三) 下午4:58 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [kennymckormick/pyskl] How can I train a gesture recognition model with a dynamic dataset? (Issue #213) Hello, thank you for your reply. There is one more question, I have learned that STGCN network classifs behaviors for consecutive frames. Did you add tracking network? I didn't see it in the configuration file. … ------------------ 原始邮件 ------------------ 发件人: "kennymckormick/pyskl" @.&gt;; 发送时间:&nbsp;2024年1月16日(星期二) 下午2:55 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [kennymckormick/pyskl] How can I train a gesture recognition model with a dynamic dataset? (Issue #213) Hello, have you trained gesture recognition with stgcn++? Can you share it? I just train simply, the config file content is below: graph = 'handmp' modality = 'j' model = dict( type='RecognizerGCN', backbone=dict( type='STGCN', in_channels=2, gcn_adaptive='init', gcn_with_res=True, tcn_type='mstcn', num_stages=6, down_stages=[6], inflate_stages=[6], graph_cfg=dict(layout=graph, mode='spatial')), cls_head=dict(type='GCNHead', num_classes=2, in_channels=128)) dataset_type = 'GestureDataset' ann_file = 'data/labdata/smoke_output_final.pkl' load_from = 'demo/hagrid.pth' train_pipeline = [ dict(type='PreNormalize2D', threshold=0, mode='auto'), dict(type='GenSkeFeat', dataset=graph, feats=[modality]), dict(type='UniformSample', clip_len=10, num_clips=1), dict(type='PoseDecode'), dict(type='FormatGCNInput', num_person=1), dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]), dict(type='ToTensor', keys=['keypoint']) ] val_pipeline = [ dict(type='PreNormalize2D', threshold=0, mode='auto'), dict(type='GenSkeFeat', dataset=graph, feats=[modality]), dict(type='UniformSample', clip_len=10, num_clips=1), dict(type='PoseDecode'), dict(type='FormatGCNInput', num_person=1), dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]), dict(type='ToTensor', keys=['keypoint']) ] test_pipeline = [ dict(type='PreNormalize2D', threshold=0, mode='auto'), dict(type='GenSkeFeat', dataset=graph, feats=[modality]), dict(type='UniformSample', clip_len=10, num_clips=1), dict(type='PoseDecode'), dict(type='FormatGCNInput', num_person=1), dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]), dict(type='ToTensor', keys=['keypoint']) ] data = dict( videos_per_gpu=16, workers_per_gpu=2, test_dataloader=dict(videos_per_gpu=1), train=dict( type='RepeatDataset', times=5, dataset=dict(type=dataset_type, ann_file=ann_file, pipeline=train_pipeline, split='labdata_train')), val=dict(type=dataset_type, ann_file=ann_file, pipeline=val_pipeline, split='labdata_val'), test=dict(type=dataset_type, ann_file=ann_file, pipeline=test_pipeline, split='labdata_val')) optimizer optimizer = dict(type='SGD', lr=0.1, momentum=0.9, weight_decay=0.0005, nesterov=True) optimizer_config = dict(grad_clip=None) learning policy lr_config = dict(policy='CosineAnnealing', min_lr=0, by_epoch=False) total_epochs = 25 checkpoint_config = dict(interval=1) evaluation = dict(interval=1, metrics=['top_k_accuracy']) log_config = dict(interval=1, hooks=[dict(type='TextLoggerHook')]) runtime settings log_level = 'INFO' work_dir = './work_dirs/stgcn++/stgcn++_labdata_hrnet/hand_j' then just use the script bash file to train — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; Sorry, I didn't. Maybe you need to try it on your own. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

Sorry, I use my own dataset which has only 2 categories, so I can't provide the images

**Comment by karryor** [comment]
OK, thank you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kennymckormick/pyskl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月19日(星期五) 中午11:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kennymckormick/pyskl] How can I train a gesture recognition model with a dynamic dataset? (Issue #213)





  
Hello, can you share the 40 categories of gesture recognition and corresponding gesture images， thank you？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "kennymckormick/pyskl" @.&gt;; 发送时间:&nbsp;2024年1月17日(星期三) 下午4:58 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [kennymckormick/pyskl] How can I train a gesture recognition model with a dynamic dataset? (Issue #213) Hello, thank you for your reply. There is one more question, I have learned that STGCN network classifs behaviors for consecutive frames. Did you add tracking network? I didn't see it in the configuration file. … ------------------ 原始邮件 ------------------ 发件人: "kennymckormick/pyskl" @.&gt;; 发送时间:&nbsp;2024年1月16日(星期二) 下午2:55 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [kennymckormick/pyskl] How can I train a gesture recognition model with a dynamic dataset? (Issue #213) Hello, have you trained gesture recognition with stgcn++? Can you share it? I just train simply, the config file content is below: graph = 'handmp' modality = 'j' model = dict( type='RecognizerGCN', backbone=dict( type='STGCN', in_channels=2, gcn_adaptive='init', gcn_with_res=True, tcn_type='mstcn', num_stages=6, down_stages=[6], inflate_stages=[6], graph_cfg=dict(layout=graph, mode='spatial')), cls_head=dict(type='GCNHead', num_classes=2, in_channels=128)) dataset_type = 'GestureDataset' ann_file = 'data/labdata/smoke_output_final.pkl' load_from = 'demo/hagrid.pth' train_pipeline = [ dict(type='PreNormalize2D', threshold=0, mode='auto'), dict(type='GenSkeFeat', dataset=graph, feats=[modality]), dict(type='UniformSample', clip_len=10, num_clips=1), dict(type='PoseDecode'), dict(type='FormatGCNInput', num_person=1), dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]), dict(type='ToTensor', keys=['keypoint']) ] val_pipeline = [ dict(type='PreNormalize2D', threshold=0, mode='auto'), dict(type='GenSkeFeat', dataset=graph, feats=[modality]), dict(type='UniformSample', clip_len=10, num_clips=1), dict(type='PoseDecode'), dict(type='FormatGCNInput', num_person=1), dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]), dict(type='ToTensor', keys=['keypoint']) ] test_pipeline = [ dict(type='PreNormalize2D', threshold=0, mode='auto'), dict(type='GenSkeFeat', dataset=graph, feats=[modality]), dict(type='UniformSample', clip_len=10, num_clips=1), dict(type='PoseDecode'), dict(type='FormatGCNInput', num_person=1), dict(type='Collect', keys=['keypoint', 'label'], meta_keys=[]), dict(type='ToTensor', keys=['keypoint']) ] data = dict( videos_per_gpu=16, workers_per_gpu=2, test_dataloader=dict(videos_per_gpu=1), train=dict( type='RepeatDataset', times=5, dataset=dict(type=dataset_type, ann_file=ann_file, pipeline=train_pipeline, split='labdata_train')), val=dict(type=dataset_type, ann_file=ann_file, pipeline=val_pipeline, split='labdata_val'), test=dict(type=dataset_type, ann_file=ann_file, pipeline=test_pipeline, split='labdata_val')) optimizer optimizer = dict(type='SGD', lr=0.1, momentum=0.9, weight_decay=0.0005, nesterov=True) optimizer_config = dict(grad_clip=None) learning policy lr_config = dict(policy='CosineAnnealing', min_lr=0, by_epoch=False) total_epochs = 25 checkpoint_config = dict(interval=1) evaluation = dict(interval=1, metrics=['top_k_accuracy']) log_config = dict(interval=1, hooks=[dict(type='TextLoggerHook')]) runtime settings log_level = 'INFO' work_dir = './work_dirs/stgcn++/stgcn++_labdata_hrnet/hand_j' then just use the script bash file to train — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; Sorry, I didn't. Maybe you need to try it on your own. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt;
  
Sorry, I use my own dataset which has only 2 categories, so I can't provide the images

**Comment by na1otname** [comment]
Could I take a look at your dataset format? I created my dataset following the instructions in the `README` located within the `tools/data` directory. However, this approach only supports training with the `PoseDataset`; it is incompatible with `GestureDataset` training, and attempting to train directly results in a dimension mismatch error. Upon examining the class implementation for `GestureDataset`, I discovered that it utilizes the confidence scores embedded within the time-series keypoint data to determine whether a specific keypoint should be filtered out.


Traceback (most recent call last):
  File "E:/Github/pyskl-main/tools/train.py", line 176, in <module>
    main()
  File "E:/Github/pyskl-main/tools/train.py", line 136, in main
    datasets = [build_dataset(cfg.data.train)]
  File "E:\Github\pyskl-main\pyskl\datasets\builder.py", line 37, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "D:\anaconda3\envs\pyskl\lib\site-packages\mmcv\utils\registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
IndexError: RepeatDataset: GestureDataset: index 2 is out of bounds for axis 3 with size 2
<img width="951" height="289" alt="Image" src="https://github.com/user-attachments/assets/8e492248-0306-4ebd-be9d-de4fa4c0d708" />
