### ISSUE TITLE
configs/rgbpose_conv3d/compress_nturgbd.py Traceback (most recent call last):   File "compress_nturgbd.py", line 5, in <module>     from pyskl.smp import * ModuleNotFoundError: No module named 'pyskl'

### ISSUE THREAD

**Issue by followingcode** [kennymckormick/pyskl#241]
root@autodl-container-3fb9439642-043bf257:~/pyskl/configs/rgbpose_conv3d# python compress_nturgbd.py
Traceback (most recent call last):
  File "compress_nturgbd.py", line 5, in <module>
    from pyskl.smp import *
ModuleNotFoundError: No module named 'pyskl'

![error](https://github.com/kennymckormick/pyskl/assets/119164984/3a59cead-36c8-4543-8a37-21b1a105ed07)

I would like to ask why when I run compress_nturgbd.py script in the terminal, I am prompted that the pyskl module is missing in line 5
ModuleNotFoundError: No module named 'pyskl'
thanks in advance @kennymckormick

**Comment by followingcode** [comment]
I found that I didn't enter my own virtual environment, and I could run it when I entered my own virtual environment, but the 130G video was found to be stuck.
