### ISSUE TITLE
#Rank issue

### ISSUE THREAD

**Issue by baigwadood** [kennymckormick/pyskl#27]
when I run tools/data/custom_2d_skeleton.py file, I get the following error:
Traceback (most recent call last):
  File "./tools/data/custom_2d_skeleton.py", line 172, in <module>
    main()
  File "./tools/data/custom_2d_skeleton.py", line 119, in main
    init_dist('pytorch', backend='nccl')
  File "/home/ubuntu/miniconda3/envs/aiguard1/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 40, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/home/ubuntu/miniconda3/envs/aiguard1/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 51, in _init_dist_pytorch
    rank = int(os.environ['RANK'])
  File "/home/ubuntu/miniconda3/envs/aiguard1/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'

Dependencies:
python 3.7
pytorch 1.11
cudatollkit 11.3
mmcv-full 1.5.0
mmdet  2.24.0
-Use single GPU
Can anyone give me some idea to solve this? Thanks!

**Comment by kennymckormick** [comment]
Hello, please check this example on how to use the provided script: https://github.com/kennymckormick/pyskl/blob/main/examples/extract_diving48_skeleton/diving48_example.ipynb

**Comment by baigwadood** [comment]
I ran the above mentioned link.


/home/ubuntu/miniconda3/envs/aiguard1/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
load checkpoint from http path: https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco-person/faster_rcnn_r50_fpn_1x_coco-person_20201216_175929-d022e227.pth
load checkpoint from http path: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth
  0%|                                                 | 0/16997 [00:00<?, ?it/s]/home/ubuntu/miniconda3/envs/aiguard1/lib/python3.7/site-packages/mmdet/datasets/utils.py:70: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
  0%|                                                 | 0/16997 [00:16<?, ?it/s]
Traceback (most recent call last):
  File "/home/ubuntu/Documents/aiguard/pyskl/tools/data/custom_2d_skeleton.py", line 172, in <module>
    main()
  File "/home/ubuntu/Documents/aiguard/pyskl/tools/data/custom_2d_skeleton.py", line 145, in main
    pose_results = pose_inference(pose_model, frames, det_results)
  File "/home/ubuntu/Documents/aiguard/pyskl/tools/data/custom_2d_skeleton.py", line 68, in pose_inference
    pose = inference_top_down_pose_model(model, f, d, format='xyxy')[0]
  File "/home/ubuntu/miniconda3/envs/aiguard1/lib/python3.7/site-packages/mmcv/utils/misc.py", line 340, in new_func
    output = old_func(*args, **kwargs)
  File "/home/ubuntu/Documents/aiguard/mmpose/mmpose/apis/inference.py", line 387, in inference_top_down_pose_model
    use_multi_frames=use_multi_frames)
  File "/home/ubuntu/Documents/aiguard/mmpose/mmpose/apis/inference.py", line 247, in _inference_single_pose_model
    data = test_pipeline(data)
  File "/home/ubuntu/Documents/aiguard/mmpose/mmpose/datasets/pipelines/shared_transform.py", line 107, in __call__
    data = t(data)
  File "/home/ubuntu/Documents/aiguard/mmpose/mmpose/datasets/pipelines/top_down_transform.py", line 289, in __call__
    c = results['center']
KeyError: 'center'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 7369) of binary: /home/ubuntu/miniconda3/envs/aiguard1/bin/python
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/aiguard1/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/miniconda3/envs/aiguard1/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/miniconda3/envs/aiguard1/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/ubuntu/miniconda3/envs/aiguard1/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/ubuntu/miniconda3/envs/aiguard1/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/ubuntu/miniconda3/envs/aiguard1/lib/python3.7/site-packages/torch/distributed/run.py", line 718, in run
    )(*cmd_args)
  File "/home/ubuntu/miniconda3/envs/aiguard1/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/miniconda3/envs/aiguard1/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/ubuntu/Documents/aiguard/pyskl/tools/data/custom_2d_skeleton.py FAILED



Can anyone give me some idea to solve this? Thanks!
