### ISSUE TITLE
test with single GPU   error

### ISSUE THREAD

**Issue by insist-arui** [kennymckormick/pyskl#38]
sir,when i test with single GPU,the error is  KeyError :"val"  and KeyError:"PoseDataset: 'val". My command is  bash tools/dist_test.sh configs/posec3d/slowonly_r50_diving48/joint.py  work_dirs/posec3d/slowonly_r50_diving48/joint/latest.pth  1 --out yaml/testwork.json --eval top_k_accuracy mean_class_accuracy           thanks for you!

**Comment by insist-arui** [comment]
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/root/pyskl/pyskl/datasets/pose_dataset.py", line 58, in __init__
    super().__init__(
  File "/root/pyskl/pyskl/datasets/base.py", line 72, in __init__
    self.video_infos = self.load_annotations()
  File "/root/pyskl/pyskl/datasets/pose_dataset.py", line 90, in load_annotations
    return self.load_pkl_annotations()
  File "/root/pyskl/pyskl/datasets/pose_dataset.py", line 98, in load_pkl_annotations
    split = set(split[self.split])
KeyError: 'val'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test.py", line 180, in <module>
    main()
  File "tools/test.py", line 134, in main
    dataset = build_dataset(cfg.data.test, dict(test_mode=True))
  File "/root/pyskl/pyskl/datasets/builder.py", line 38, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/root/.local/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "PoseDataset: 'val'"
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 184) of binary: /root/.local/conda/envs/open-mmlab/bin/python
Traceback (most recent call last):
  File "/root/.local/conda/envs/open-mmlab/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/.local/conda/envs/open-mmlab/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.local/conda/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/root/.local/conda/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/root/.local/conda/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/root/.local/conda/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/root/.local/conda/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/.local/conda/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(

**Comment by insist-arui** [comment]
in confige  .py i change the val to test in  [test=dict(type=dataset_type, ann_file=ann_file, split='val', pipeline=test_pipeline)]
