### ISSUE TITLE
KeyError 'LoadImageFromFile'

### ISSUE THREAD

**Issue by hthanhle** [kennymckormick/pyskl#78]
I got the following error when running the code `results = inference_recognizer(model, fake_anno)` in `demo_skeleton.py`:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-39-3ad26ccbf498>", line 1, in <module>
    results = inference_recognizer(model, fake_anno)
  File "/data/video_action_detection/pyskl/pyskl/apis/inference.py", line 163, in inference_recognizer
    test_pipeline = Compose(test_pipeline)
  File "/data/video_action_detection/pyskl/pyskl/datasets/pipelines/compose.py", line 23, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/utils/registry.py", line 62, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'LoadImageFromFile is not in the pipeline registry'
```
My dependencies:
MMCV full: 1.6.1
MMDet: 2.25.1
MMPose: 0.28.1

Any help or suggestions would be greatly appreciated!

**Comment by kennymckormick** [comment]
Hi, hthanhle,
Guess you wrongly used a detection config for training in PYSKL, PYSKL doesn't have the `LoadImageFromFile` component. Please only use the detection config for demo and inference.
