### ISSUE TITLE
RuntimeError: Distributed package doesn't have NCCL built in

### ISSUE THREAD

**Issue by nngg11** [kennymckormick/pyskl#79]
Hello, I am trying to test/train a model and I get the error "RuntimeError: Distributed package doesn't have NCCL built in". I am training on Windows with one GPU using torch1.11.0+cu113.

Is there a tweak or fix to this error related to PyTorch?

Here is the traceback after running the test command for further information:
```
NOTE: Redirects are currently not supported in Windows or MacOs.
C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\distributed\launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [DESKTOP-7BNNAUJ]:29995 (system error: 
10049 - The requested address is not valid in its context.).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [DESKTOP-7BNNAUJ]:29995 (system error: 
10049 - The requested address is not valid in its context.).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [DESKTOP-7BNNAUJ]:29995 (system error: 
10049 - The requested address is not valid in its context.).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [DESKTOP-7BNNAUJ]:29995 (system error: 
10049 - The requested address is not valid in its context.).
Traceback (most recent call last):
  File "C:\Users\usuario\Desktop\Fudan\Research\Fudan+Zhejiang\Official Implementations\pyskl\tools\test.py", line 176, in <module>
    main()
  File "C:\Users\usuario\Desktop\Fudan\Research\Fudan+Zhejiang\Official Implementations\pyskl\tools\test.py", line 129, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\site-packages\mmcv\runner\dist_utils.py", line 41, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\site-packages\mmcv\runner\dist_utils.py", line 64, in _init_dist_pytorch
    dist.init_process_group(backend=backend, **kwargs)
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\distributed\distributed_c10d.py", line 602, in init_process_group
    default_pg = _new_process_group_helper(
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\distributed\distributed_c10d.py", line 727, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 23932) of binary: C:\Users\usuario\AppData\Local\Programs\Python\Python39\python.exe
Traceback (most recent call last):
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\distributed\launch.py", line 193, in <module>
    main()
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\distributed\launch.py", line 189, in main
    launch(args)
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\distributed\launch.py", line 174, in launch
    run(args)
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\distributed\run.py", line 715, in run
    elastic_launch(
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\distributed\launcher\api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\distributed\launcher\api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
tools/test.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-08-19_12:10:41
  host      : DESKTOP-7BNNAUJ
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 23932)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by kennymckormick** [comment]
Hi, nngg11, 
I'm not sure if this codebase supports training / testing on windows since I have never tried this before. I only use linux-based systems, and I guess there will be some problems if you run training / testing on windows. But maybe you can refer to this issue: https://github.com/kennymckormick/pyskl/issues/64, seems some users have tried testing on windows successfully.

**Comment by nngg11** [comment]
Switching the backend to gloo works fine. Thank you!
